-- K-Admission PostgreSQL reference schema v1.2
-- University Data Plane / PostgreSQL 15+ compatible baseline
-- UUID values are generated by the application layer.
--
-- v1.2 (2026-09-27) folds the repository migrations 0002·0003·0005·0006 and the audit
-- append-only trigger of 0004 into the reference schema. Roles and grants stay a separate
-- operational script (different per environment). Spec discrepancy register:
--   D-21 config/deadline two-person approval · D-23 deadline_policy lifecycle
--   D-25 one open reconciliation exception per type · D-29 one department per admission type,
--        cancelled applications excluded · D-35 signed append-only activation_record
--   D-41 audit_event append-only

CREATE SCHEMA IF NOT EXISTS kadmission;
SET search_path TO kadmission, public;

CREATE TABLE university (
  id varchar(32) PRIMARY KEY,
  name varchar(200) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admission_cycle (
  id uuid PRIMARY KEY,
  university_id varchar(32) NOT NULL REFERENCES university(id),
  admission_year smallint NOT NULL,
  name varchar(200) NOT NULL,
  opens_at timestamptz NOT NULL,
  closes_at timestamptz NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('DRAFT','OPEN','CLOSED','ARCHIVED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (university_id, admission_year, name),
  CHECK (opens_at < closes_at)
);

CREATE TABLE admission_type (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  code varchar(64) NOT NULL,
  name varchar(200) NOT NULL,
  fee_amount numeric(12,2) NOT NULL CHECK (fee_amount >= 0),
  active boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (cycle_id, code)
);

CREATE TABLE department (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  code varchar(64) NOT NULL,
  name varchar(200) NOT NULL,
  quota integer NULL CHECK (quota IS NULL OR quota >= 0),
  active boolean NOT NULL DEFAULT true,
  UNIQUE (cycle_id, code)
);

CREATE TABLE deadline_policy (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  version varchar(64) NOT NULL,
  mode varchar(48) NOT NULL CHECK (mode IN (
    'FINALIZED_COMMIT_BEFORE_DEADLINE',
    'REQUEST_RECEIVED_BEFORE_DEADLINE',
    'PAYMENT_APPROVED_BEFORE_DEADLINE'
  )),
  deadline_at timestamptz NOT NULL,
  approved_by_1 varchar(128) NULL,
  approved_by_2 varchar(128) NULL,
  approved_at timestamptz NULL,
  activated_at timestamptz NULL,
  policy_hash varchar(128) NOT NULL,
  immutable_snapshot jsonb NOT NULL,
  -- D-23: lifecycle. Which policy is in force is decided by activated_at order
  -- (scheduled activation), so there is no ACTIVE/RETIRED to keep in sync.
  status varchar(24) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','APPROVED','ACTIVATED')),
  created_by varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (cycle_id, version),
  CHECK (approved_by_1 <> approved_by_2),
  CONSTRAINT deadline_policy_two_person_approval CHECK (
    status = 'DRAFT'
    OR (approved_by_1 IS NOT NULL AND approved_by_2 IS NOT NULL
        AND approved_by_1 <> approved_by_2 AND approved_at IS NOT NULL)
  ),
  CONSTRAINT deadline_policy_activation_state CHECK (
    (status = 'ACTIVATED') = (activated_at IS NOT NULL)
  ),
  CONSTRAINT deadline_policy_no_self_approval CHECK (
    (approved_by_1 IS NULL OR approved_by_1 <> created_by)
    AND (approved_by_2 IS NULL OR approved_by_2 <> created_by)
  )
);

CREATE TABLE config_version (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  version varchar(64) NOT NULL,
  status varchar(24) NOT NULL CHECK (status IN ('DRAFT','APPROVED','ACTIVE','RETIRED')),
  config_json jsonb NOT NULL,
  config_hash varchar(128) NOT NULL,
  created_by varchar(128) NOT NULL,
  approved_by_1 varchar(128),
  approved_by_2 varchar(128),
  created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz,
  activated_at timestamptz,
  UNIQUE (cycle_id, version),
  -- D-21: effective states need two distinct approvers, never the author.
  CONSTRAINT config_version_two_person_approval CHECK (
    status NOT IN ('APPROVED','ACTIVE')
    OR (approved_by_1 IS NOT NULL
        AND approved_by_2 IS NOT NULL
        AND approved_by_1 <> approved_by_2)
  ),
  CONSTRAINT config_version_approver_not_creator CHECK (
    (approved_by_1 IS NULL OR approved_by_1 <> created_by)
    AND (approved_by_2 IS NULL OR approved_by_2 <> created_by)
  ),
  CONSTRAINT config_version_active_has_timestamp CHECK (
    status <> 'ACTIVE' OR activated_at IS NOT NULL
  )
);
-- D-21: one ACTIVE config per cycle.
CREATE UNIQUE INDEX uq_config_active_per_cycle
  ON config_version(cycle_id) WHERE status = 'ACTIVE';

CREATE TABLE applicant (
  id uuid PRIMARY KEY,
  subject_token varchar(160) NOT NULL UNIQUE,
  pii_ciphertext bytea NOT NULL,
  pii_key_version varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE applicant_identifier (
  id uuid PRIMARY KEY,
  applicant_id uuid NOT NULL REFERENCES applicant(id) ON DELETE CASCADE,
  identifier_type varchar(32) NOT NULL,
  identifier_ciphertext bytea NOT NULL,
  key_version varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (applicant_id, identifier_type)
);

CREATE TABLE application (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  applicant_id uuid NOT NULL REFERENCES applicant(id),
  admission_type_id uuid NOT NULL REFERENCES admission_type(id),
  department_id uuid NOT NULL REFERENCES department(id),
  status varchar(24) NOT NULL CHECK (status IN (
    'DRAFT','READY','PAYMENT_PENDING','PAID',
    'FINALIZING','FINALIZED','CANCELLED','EXPIRED'
  )),
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  last_saved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
-- D-29: one valid application per admission type — "하나의 전형에서는 하나의 모집단위에만
-- 지원할 수 있음" (대학입학전형기본사항). Cancelled applications do not block re-applying.
CREATE UNIQUE INDEX uq_application_active_natural_key
  ON application(cycle_id, applicant_id, admission_type_id)
  WHERE status <> 'CANCELLED';
CREATE INDEX idx_application_applicant_cycle ON application(applicant_id, cycle_id);
CREATE INDEX idx_application_status_updated ON application(status, updated_at);

CREATE TABLE application_field_value (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  field_code varchar(128) NOT NULL,
  schema_version varchar(64) NOT NULL,
  value_json jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (application_id, field_code)
);

CREATE TABLE document (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  document_type varchar(64) NOT NULL,
  object_key varchar(512) NOT NULL,
  original_filename varchar(512) NOT NULL,
  media_type varchar(128) NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  sha256_hex char(64) NOT NULL,
  status varchar(24) NOT NULL CHECK (status IN ('UPLOADING','QUARANTINED','AVAILABLE','REJECTED','DELETED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_document_application_status ON document(application_id, status);

CREATE TABLE document_scan (
  id uuid PRIMARY KEY,
  document_id uuid NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  scanner varchar(64) NOT NULL,
  engine_version varchar(64),
  result varchar(24) NOT NULL CHECK (result IN ('PENDING','CLEAN','MALICIOUS','ERROR')),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  scanned_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payment (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id),
  provider varchar(64) NOT NULL,
  provider_tx_id varchar(160),
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  currency char(3) NOT NULL DEFAULT 'KRW',
  status varchar(24) NOT NULL CHECK (status IN ('CREATED','PENDING','UNKNOWN','CONFIRMED','FAILED','CANCELLED','REFUNDED')),
  provider_approved_at timestamptz,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_payment_provider_tx ON payment(provider, provider_tx_id) WHERE provider_tx_id IS NOT NULL;
CREATE INDEX idx_payment_application_status ON payment(application_id, status);

CREATE TABLE payment_event (
  id uuid PRIMARY KEY,
  payment_id uuid NOT NULL REFERENCES payment(id) ON DELETE CASCADE,
  event_type varchar(64) NOT NULL,
  provider_event_id varchar(160),
  payload_hash varchar(128) NOT NULL,
  payload_redacted jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_payment_provider_event ON payment_event(payment_id, provider_event_id) WHERE provider_event_id IS NOT NULL;

CREATE TABLE submission (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL UNIQUE REFERENCES application(id),
  application_number varchar(80) NOT NULL UNIQUE,
  requested_at timestamptz NOT NULL,
  payment_verified_at timestamptz NOT NULL,
  finalized_at timestamptz NOT NULL,
  deadline_policy_version varchar(64) NOT NULL,
  config_version varchar(64) NOT NULL,
  server_clock_offset_ms integer NOT NULL DEFAULT 0,
  evidence_hash varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_record (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  operation varchar(64) NOT NULL,
  idempotency_key varchar(200) NOT NULL,
  request_hash varchar(128) NOT NULL,
  response_status integer,
  response_body jsonb,
  state varchar(20) NOT NULL CHECK (state IN ('PROCESSING','COMPLETED','FAILED')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (application_id, operation, idempotency_key)
);

CREATE TABLE consent_record (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  consent_code varchar(128) NOT NULL,
  policy_version varchar(64) NOT NULL,
  granted boolean NOT NULL,
  granted_at timestamptz NOT NULL,
  evidence_hash varchar(128) NOT NULL,
  UNIQUE (application_id, consent_code, policy_version)
);

CREATE TABLE audit_event (
  id uuid PRIMARY KEY,
  application_id uuid REFERENCES application(id),
  actor_type varchar(24) NOT NULL,
  actor_id varchar(160),
  action varchar(96) NOT NULL,
  result varchar(24) NOT NULL,
  trace_id varchar(80),
  config_version varchar(64),
  policy_version varchar(64),
  source_ip_hash varchar(128),
  prev_hash varchar(128),
  event_hash varchar(128) NOT NULL,
  details_redacted jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL
);
CREATE INDEX idx_audit_application_time ON audit_event(application_id, occurred_at);

-- D-41: audit events are append-only for every account, owner included.
-- (A superuser disabling triggers is out of reach inside the DB — WORM storage covers that.)
CREATE OR REPLACE FUNCTION audit_event_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_event 는 추가만 가능하다 (% 거부)', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_event_no_update
  BEFORE UPDATE OR DELETE ON audit_event
  FOR EACH ROW EXECUTE FUNCTION audit_event_append_only();
-- TRUNCATE bypasses row triggers.
CREATE TRIGGER audit_event_no_truncate
  BEFORE TRUNCATE ON audit_event
  FOR EACH STATEMENT EXECUTE FUNCTION audit_event_append_only();

CREATE TABLE outbox_event (
  id uuid PRIMARY KEY,
  aggregate_type varchar(48) NOT NULL DEFAULT 'APPLICATION',
  aggregate_id uuid NOT NULL,
  aggregate_sequence bigint NOT NULL CHECK (aggregate_sequence > 0),
  event_type varchar(160) NOT NULL,
  schema_version varchar(32) NOT NULL,
  payload jsonb NOT NULL,
  payload_hash varchar(128) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENDING','SENT','DEAD')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  UNIQUE (aggregate_id, aggregate_sequence)
);
CREATE INDEX idx_outbox_pending ON outbox_event(created_at) WHERE status IN ('PENDING','SENDING');

CREATE TABLE sync_receipt (
  id uuid PRIMARY KEY,
  outbox_event_id uuid NOT NULL UNIQUE REFERENCES outbox_event(id),
  central_receipt_id varchar(160) NOT NULL,
  acknowledged_at timestamptz NOT NULL,
  central_sequence bigint,
  receipt_hash varchar(128) NOT NULL
);

CREATE TABLE reconciliation_exception (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id),
  exception_type varchar(96) NOT NULL,
  severity varchar(16) NOT NULL CHECK (severity IN ('INFO','WARN','HIGH','CRITICAL')),
  state varchar(20) NOT NULL CHECK (state IN ('OPEN','AUTO_RESOLVED','MANUAL_REVIEW','RESOLVED')),
  facts jsonb NOT NULL,
  detected_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolution_code varchar(96),
  resolved_by varchar(128)
);
CREATE INDEX idx_recon_open ON reconciliation_exception(severity, detected_at)
  WHERE state IN ('OPEN','MANUAL_REVIEW');
-- D-25: periodic reconciliation must not stack the same open mismatch.
-- Resolved ones may reopen as a new incident.
CREATE UNIQUE INDEX uq_recon_open_per_type
  ON reconciliation_exception(application_id, exception_type)
  WHERE state IN ('OPEN','MANUAL_REVIEW');

-- D-35: signed record of every deadline/config activation (who, when, why).
-- Policy/config rows are "what"; this row is "who applied it, when and why". Append-only.
CREATE TABLE activation_record (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  subject_type varchar(24) NOT NULL CHECK (subject_type IN ('DEADLINE_POLICY','CONFIG_VERSION')),
  subject_id uuid NOT NULL,
  subject_version varchar(64) NOT NULL,
  kind varchar(16) NOT NULL CHECK (kind IN ('ACTIVATE','EXTEND','ROLLBACK')),
  effective_at timestamptz NOT NULL,
  operator_id varchar(128) NOT NULL,
  reason text,
  -- Admissions office decision document number; mandatory for extensions.
  decision_ref varchar(128),
  supersedes_version varchar(64),
  payload jsonb NOT NULL,
  payload_hash varchar(128) NOT NULL,
  signature text NOT NULL,
  key_id varchar(64) NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CHECK (kind = 'ACTIVATE' OR (reason IS NOT NULL AND length(btrim(reason)) > 0)),
  CHECK (kind <> 'EXTEND' OR (decision_ref IS NOT NULL AND length(btrim(decision_ref)) > 0))
);
CREATE INDEX idx_activation_subject
  ON activation_record(subject_type, subject_id, recorded_at);
CREATE INDEX idx_activation_cycle
  ON activation_record(cycle_id, recorded_at);

CREATE OR REPLACE FUNCTION activation_record_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'activation_record 는 추가만 가능하다 (% 거부)', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER activation_record_no_update
  BEFORE UPDATE OR DELETE ON activation_record
  FOR EACH ROW EXECUTE FUNCTION activation_record_append_only();
CREATE TRIGGER activation_record_no_truncate
  BEFORE TRUNCATE ON activation_record
  FOR EACH STATEMENT EXECUTE FUNCTION activation_record_append_only();
