-- K-Admission PostgreSQL reference schema v1.1
-- University Data Plane / PostgreSQL 15+ compatible baseline
-- UUID values are generated by the application layer.

CREATE SCHEMA IF NOT EXISTS kadmission;
SET search_path TO kadmission, public;

CREATE TABLE university (
  id varchar(32) PRIMARY KEY,
  name varchar(200) NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admission_cycle (
  id uuid PRIMARY KEY,
  university_id varchar(32) NOT NULL REFERENCES university(id),
  admission_year smallint NOT NULL,
  name varchar(200) NOT NULL,
  opens_at timestamptz NOT NULL,
  closes_at timestamptz NOT NULL,
  status varchar(20) NOT NULL CHECK (status IN ('DRAFT','OPEN','CLOSED','ARCHIVED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (university_id, admission_year, name),
  CHECK (opens_at < closes_at)
);

CREATE TABLE admission_type (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  code varchar(64) NOT NULL,
  name varchar(200) NOT NULL,
  fee_amount numeric(12,2) NOT NULL CHECK (fee_amount >= 0),
  active boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (cycle_id, code)
);

CREATE TABLE department (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  code varchar(64) NOT NULL,
  name varchar(200) NOT NULL,
  quota integer NULL CHECK (quota IS NULL OR quota >= 0),
  active boolean NOT NULL DEFAULT true,
  UNIQUE (cycle_id, code)
);

CREATE TABLE deadline_policy (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  version varchar(64) NOT NULL,
  mode varchar(48) NOT NULL CHECK (mode IN (
    'FINALIZED_COMMIT_BEFORE_DEADLINE',
    'REQUEST_RECEIVED_BEFORE_DEADLINE',
    'PAYMENT_APPROVED_BEFORE_DEADLINE'
  )),
  deadline_at timestamptz NOT NULL,
  approved_by_1 varchar(128) NOT NULL,
  approved_by_2 varchar(128) NOT NULL,
  approved_at timestamptz NOT NULL,
  activated_at timestamptz NULL,
  policy_hash varchar(128) NOT NULL,
  immutable_snapshot jsonb NOT NULL,
  UNIQUE (cycle_id, version),
  CHECK (approved_by_1 <> approved_by_2)
);

CREATE TABLE config_version (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  version varchar(64) NOT NULL,
  status varchar(24) NOT NULL CHECK (status IN ('DRAFT','APPROVED','ACTIVE','RETIRED')),
  config_json jsonb NOT NULL,
  config_hash varchar(128) NOT NULL,
  created_by varchar(128) NOT NULL,
  approved_by_1 varchar(128),
  approved_by_2 varchar(128),
  created_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz,
  activated_at timestamptz,
  UNIQUE (cycle_id, version)
);

CREATE TABLE applicant (
  id uuid PRIMARY KEY,
  subject_token varchar(160) NOT NULL UNIQUE,
  pii_ciphertext bytea NOT NULL,
  pii_key_version varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE applicant_identifier (
  id uuid PRIMARY KEY,
  applicant_id uuid NOT NULL REFERENCES applicant(id) ON DELETE CASCADE,
  identifier_type varchar(32) NOT NULL,
  identifier_ciphertext bytea NOT NULL,
  key_version varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (applicant_id, identifier_type)
);

CREATE TABLE application (
  id uuid PRIMARY KEY,
  cycle_id uuid NOT NULL REFERENCES admission_cycle(id),
  applicant_id uuid NOT NULL REFERENCES applicant(id),
  admission_type_id uuid NOT NULL REFERENCES admission_type(id),
  department_id uuid NOT NULL REFERENCES department(id),
  status varchar(24) NOT NULL CHECK (status IN (
    'DRAFT','READY','PAYMENT_PENDING','PAID',
    'FINALIZING','FINALIZED','CANCELLED','EXPIRED'
  )),
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  last_saved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (cycle_id, applicant_id, admission_type_id, department_id)
);
CREATE INDEX idx_application_applicant_cycle ON application(applicant_id, cycle_id);
CREATE INDEX idx_application_status_updated ON application(status, updated_at);

CREATE TABLE application_field_value (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  field_code varchar(128) NOT NULL,
  schema_version varchar(64) NOT NULL,
  value_json jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (application_id, field_code)
);

CREATE TABLE document (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  document_type varchar(64) NOT NULL,
  object_key varchar(512) NOT NULL,
  original_filename varchar(512) NOT NULL,
  media_type varchar(128) NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  sha256_hex char(64) NOT NULL,
  status varchar(24) NOT NULL CHECK (status IN ('UPLOADING','QUARANTINED','AVAILABLE','REJECTED','DELETED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_document_application_status ON document(application_id, status);

CREATE TABLE document_scan (
  id uuid PRIMARY KEY,
  document_id uuid NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  scanner varchar(64) NOT NULL,
  engine_version varchar(64),
  result varchar(24) NOT NULL CHECK (result IN ('PENDING','CLEAN','MALICIOUS','ERROR')),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  scanned_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payment (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id),
  provider varchar(64) NOT NULL,
  provider_tx_id varchar(160),
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  currency char(3) NOT NULL DEFAULT 'KRW',
  status varchar(24) NOT NULL CHECK (status IN ('CREATED','PENDING','UNKNOWN','CONFIRMED','FAILED','CANCELLED','REFUNDED')),
  provider_approved_at timestamptz,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_payment_provider_tx ON payment(provider, provider_tx_id) WHERE provider_tx_id IS NOT NULL;
CREATE INDEX idx_payment_application_status ON payment(application_id, status);

CREATE TABLE payment_event (
  id uuid PRIMARY KEY,
  payment_id uuid NOT NULL REFERENCES payment(id) ON DELETE CASCADE,
  event_type varchar(64) NOT NULL,
  provider_event_id varchar(160),
  payload_hash varchar(128) NOT NULL,
  payload_redacted jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_payment_provider_event ON payment_event(payment_id, provider_event_id) WHERE provider_event_id IS NOT NULL;

CREATE TABLE submission (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL UNIQUE REFERENCES application(id),
  application_number varchar(80) NOT NULL UNIQUE,
  requested_at timestamptz NOT NULL,
  payment_verified_at timestamptz NOT NULL,
  finalized_at timestamptz NOT NULL,
  deadline_policy_version varchar(64) NOT NULL,
  config_version varchar(64) NOT NULL,
  server_clock_offset_ms integer NOT NULL DEFAULT 0,
  evidence_hash varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_record (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  operation varchar(64) NOT NULL,
  idempotency_key varchar(200) NOT NULL,
  request_hash varchar(128) NOT NULL,
  response_status integer,
  response_body jsonb,
  state varchar(20) NOT NULL CHECK (state IN ('PROCESSING','COMPLETED','FAILED')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (application_id, operation, idempotency_key)
);

CREATE TABLE consent_record (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id) ON DELETE CASCADE,
  consent_code varchar(128) NOT NULL,
  policy_version varchar(64) NOT NULL,
  granted boolean NOT NULL,
  granted_at timestamptz NOT NULL,
  evidence_hash varchar(128) NOT NULL,
  UNIQUE (application_id, consent_code, policy_version)
);

CREATE TABLE audit_event (
  id uuid PRIMARY KEY,
  application_id uuid REFERENCES application(id),
  actor_type varchar(24) NOT NULL,
  actor_id varchar(160),
  action varchar(96) NOT NULL,
  result varchar(24) NOT NULL,
  trace_id varchar(80),
  config_version varchar(64),
  policy_version varchar(64),
  source_ip_hash varchar(128),
  prev_hash varchar(128),
  event_hash varchar(128) NOT NULL,
  details_redacted jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL
);
CREATE INDEX idx_audit_application_time ON audit_event(application_id, occurred_at);

CREATE TABLE outbox_event (
  id uuid PRIMARY KEY,
  aggregate_type varchar(48) NOT NULL DEFAULT 'APPLICATION',
  aggregate_id uuid NOT NULL,
  aggregate_sequence bigint NOT NULL CHECK (aggregate_sequence > 0),
  event_type varchar(160) NOT NULL,
  schema_version varchar(32) NOT NULL,
  payload jsonb NOT NULL,
  payload_hash varchar(128) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENDING','SENT','DEAD')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  UNIQUE (aggregate_id, aggregate_sequence)
);
CREATE INDEX idx_outbox_pending ON outbox_event(created_at) WHERE status IN ('PENDING','SENDING');

CREATE TABLE sync_receipt (
  id uuid PRIMARY KEY,
  outbox_event_id uuid NOT NULL UNIQUE REFERENCES outbox_event(id),
  central_receipt_id varchar(160) NOT NULL,
  acknowledged_at timestamptz NOT NULL,
  central_sequence bigint,
  receipt_hash varchar(128) NOT NULL
);

CREATE TABLE reconciliation_exception (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES application(id),
  exception_type varchar(96) NOT NULL,
  severity varchar(16) NOT NULL CHECK (severity IN ('INFO','WARN','HIGH','CRITICAL')),
  state varchar(20) NOT NULL CHECK (state IN ('OPEN','AUTO_RESOLVED','MANUAL_REVIEW','RESOLVED')),
  facts jsonb NOT NULL,
  detected_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolution_code varchar(96),
  resolved_by varchar(128)
);
CREATE INDEX idx_recon_open ON reconciliation_exception(severity, detected_at)
  WHERE state IN ('OPEN','MANUAL_REVIEW');
