apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: univ-b
  namespace: kadmission-app
spec:
  interval: 5m
  timeout: 10m
  releaseName: univ-b
  targetNamespace: kadmission-app
  storageNamespace: kadmission-app
  serviceAccountName: release-controller
  chart:
    spec:
      chart: ./deploy/charts/k-admission
      sourceRef:
        kind: GitRepository
        name: wonseoro
        namespace: kadmission-app
      reconcileStrategy: Revision
      valuesFiles:
        - deploy/charts/k-admission/values-s.yaml
        - deploy/universities/UNIV-B/values.yaml
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
